### ISSUE TITLE
Setup Assistance for Tauri v1

### ISSUE THREAD

**Issue by rawru** [zzzgydi/auto-launch#17]
hello! i am quite new to tauri and rust, so please bare with me...

(i am aware with the autostart plugin in tauri but i dont use node nor npm and so i cant use the plugin... im also staying away from tauri v2 until its full stable release)

in the AutoLaunchBuilder... there is a `.set_app_path()`. How is one to able to get the path?

also... is it possible to access the autolauch from a tauri command?

example:
```rs
#[tauri::command]
fn allow_autostart(allow: bool) -> TauriResult<()> {
    // use auto here!
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            allow_autostart
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");

    
    let auto = AutoLaunchBuilder::new()
        .set_app_name("namae")
        .set_app_path("/path/to/the-app???")
        .set_use_launch_agent(true)
        .build()
        .unwrap();
}
```

thank you for your patience with me and my ever-so-noobness!!!!

**Comment by zzzgydi** [comment]
Here is a example to show you how to get the `app_path`, https://github.com/zzzgydi/clash-verge/blob/9df1115380f8fa80c11f8e7554b2e47580ea1efa/src-tauri/src/core/sysopt.rs#L140

And you can use a static variable, such as `OnceCell<AutoLaunch>`, to save the `AutoLaunch` instance so that it can be accessed from anywhere.
